services:
  - type: web
    name: smartretail-analytics-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health
